apiVersion: v1 # Kubernetes API version
kind: Service # Type de ressource Kubernetes que nous créons
metadata: # Métadonnées du type de ressource que nous créons
  name: spring-test-service
spec:
  selector:
    app: spring-test-app
  ports:
    - protocol: "TCP"
      port: 8080 # Le port sur lequel le service est exécuté dans le cluster.
      targetPort: 8080 # Le port exposé par le service
  type: LoadBalancer # le type de service. LoadBalancer indique que notre service sera externe.
---
apiVersion: apps/v1
kind: Deployment # Type de ressource Kubernetes que nous créons
metadata:
  name: spring-test-app
spec:
  selector:
    matchLabels:
      app: spring-test-app
  replicas: 2 # Nombre de répliques qui seront créées pour ce déploiement
  template:
    metadata:
      labels:
        app: spring-test-app
    spec:
      containers:
        - name: spring-test-app
          image: spring-boot-test  # Image qui sera utilisée pour les conteneurs dans le cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # Le port sur lequel le conteneur fonctionne dans le cluster.